// STEPS 1 THROUGH 6 GO IN A SEPARATE FILE!!!

// STEP 8:  IDENTIFICATION COMMENTS GO HERE

// STEP 8:  THE IMPORT STATEMENTS GO HERE

public class FLast_Lab08	// STEP 8:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		/* STEP 9:	DECLARE A VARIABLE FOR THE USER INPUT FOR RADIUS
					CONSOLE INPUT:  DECLARE A SCANNER OBJECT
					DIALOG INPUT:  DECLARE A STRING FOR TEMPORARY STORAGE */

		/* STEP 10:	CIRCLE 1:  USE THE NO-ARG CONSTRUCTOR
					CIRCLE 2:  HARD CODE A VALUE FOR THE RADIUS
					CIRCLE 3:  PROMPT THE USER FOR THE RADIUS,
							   PASS THE INPUT VARIABLE TO THE CONSTRUCTOR */

		/* STEP 11: DISPLAY THE RADIUS, DIAMETER, AREA, AND CIRCUMFERENCE
					OF EACH CIRCLE INDIVIDUALLY (12 VALUES TO DISPLAY) */

		/* STEP 12: PROMPT THE USER FOR A NEW RADIUS
					USE THE MUTATOR METHOD TO CHANGE THE RADIUS OF A CIRCLE
					DISPLAY THE RADIUS, DIAMETER, AREA, AND CIRCUMFERENCE
						OF THE CHANGED CIRCLE */
	}
}