// STEP 2:  IDENTIFICATION COMMENTS GO HERE

// STEP 2:  THE IMPORT STATEMENT GOES HERE

public class FLast_Lab06	// STEP 2:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		/* STEP 3:  DECLARE A VARIABLE TO STORE USER INPUT
					DECLARE A SCANNER OBJECT */

		/* STEP 4:  DISPLAY THE MENU
					OBTAIN THE USER'S CHOICE */

		// STEP 6:  CALL THE VOID METHOD WITH THE INPUT VARIABLE AS THE ARGUMENT
	}

	/* STEP 5:  WRITE THE VOID METHOD DEFINITION WITH A SINGLE PARAMETER HERE
				USE A DECISION STRUCTURE TO COMPARE THE PARAMETER TO EACH VALUE
				DISPLAY THE NICKNAME THAT MATCHES THE PARAMETER VALUE
				DISPLAY AN ERROR MESSAGE IF THE PARAMETER DOES NOT MATCH
				    ANY VALUE IN THE MENU */
}