// STEP 2:  IDENTIFICATION COMMENTS GO HERE

// STEP 2:  THE IMPORT STATEMENT(S) GO(ES) HERE

public class FLast_Lab04	// STEP 2:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		// STEP 3:  DECLARE THREE NUMERIC VARIABLES
		// STEP 4:	DECLARE OBJECT(S) NEEDED FOR INPUT, FORMATTING

		/* STEP 5:  WRITE A LOOP THAT EXECUTES FOR TWELVE MONTHS
					GET THE SAVINGS AMOUNT FOR THE CURRENT MONTH
					ADD THE MONTHLY AMOUNT TO THE SUM OF THE AMOUNTS SAVED */

		/* STEP 6:  DISPLAY TOTAL SAVED WITH PROPER FORMATTING
		            (USE PRINTF OR DECIMALFORMAT) */

		// STEP 7:  USE A DECISION STRUCTURE TO DISPLAY A CLOSING MESSAGE
	}
}