// STEP 2:  IDENTIFICATION COMMENTS GO HERE

// STEP 2:  THE IMPORT STATEMENT(S) GO(ES) HERE

public class FLast_Lab10	// STEP 2:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		/* STEP 3:  DECLARATIONS
		   - TWO ARRAYS, ONE FOR HIGHS AND ONE FOR LOWS (DECIMAL VALUES)
		   - A SCANNER OBJECT AND (OPTIONALLY) A DECIMALFORMAT OBJECT
		   - (OPTIONALLY) A VARIABLE OR ARRAY FOR THE AVERAGES */

		/* STEP 4:  USE A LOOP TO OBTAIN INPUT FOR ALL 12 ELEMENTS IN BOTH
					ARRAYS, ASKING THE USER FOR EACH VALUE */

		// STEP 5:  DISPLAY THE COLUMN HEADINGS

		/* STEP 6:  USE A LOOP TO DISPLAY THE MONTH NUMBER AND HIGH, LOW,
					AND AVERAGE TEMPERATURES FOR EACH MONTH */
	}
}