// STEP 3:  IDENTIFICATION COMMENTS GO HERE

// STEP 4:  THE IMPORT STATEMENTS GO HERE

public class FLast_Lab03	// STEP 3:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		// STEP 5:  DECLARE VARIABLES HERE (INCLUDING A DECIMALFORMAT OBJECT)

		/* STEP 6:  USE INPUT DIALOGS TO PROMPT THE USER AND OBTAIN INPUT IN
					STRING FORM
		            CONVERT EACH INPUT VALUE TO A NUMERIC FORM USING A PARSE 
		            METHOD */

		// STEP 7:  CALCULATE VALUES USING IF AND ASSIGNMENT STATEMENTS

		/* STEP 8:  DISPLAY RESULTS IN DIALOGS WITH PROPER FORMATTING
		            (USE DECIMALFORMAT) */
	}
}