// STEP 2:  IDENTIFICATION COMMENTS GO HERE

// STEP 2:  THE IMPORT STATEMENTS GO HERE

public class FLast_Lab05	// STEP 2:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)	// STEP 2:  MODIFY HEADER FOR EXCEPTIONS
	{
		/* STEP 3:  DECLARE THREE PRIMITIVE VARIABLES
					DECLARE TWO CONSTANTS (OPTIONAL) */

		/* STEP 4:  DECLARE FILE OBJECT, CHECK FOR EXISTENCE
					DECLARE SCANNER OBJECT
					DECLARE TWO PRINTWRITER OBJECTS */

		/* STEP 5:  LOOP AS LONG AS THERE IS MORE DATA TO READ
					READ THREE VALUES FROM THE FILE
					WRITE TO FIRST OUTPUT FILE IF HIGH IS HOT
					WRITE TO SECOND OUTPUT FILE IF LOW IS COLD */

		/* STEP 6:  CLOSE ALL THREE FILES */
	}
}