// STEP 9:  IDENTIFICATION COMMENTS GO HERE

// STEP 9:  THE IMPORT STATEMENT GOES HERE

public class FLast_Lab09	// STEP 9:  CHANGE THIS TO MATCH YOUR FILE NAME
{
	public static void main(String[] args)
	{
		/* STEP 10:  DECLARE AT LEAST ONE VARIABLE FOR THE USER INPUT FOR THE
						QUANTITY OF THE ORDER OR CANCELLATION
					 CONSOLE INPUT:  DECLARE A SCANNER OBJECT
					 DIALOG INPUT:  DECLARE A STRING FOR TEMPORARY STORAGE */

		/* STEP 11:  DECLARE AT LEAST ONE ORDERS OBJECT USING ONE OF THE
					 TWO CONSTRUCTORS */

		/* STEP 12:  PERFORM ONE ORDER FOR EACH ATTRIBUTE
					 PERFORM ONE CANCELLATION FOR EACH ATTRIBUTE
					 AT LEAST ONE ORDER AND ONE CANCELLATION SHOULD BE
						USER-DRIVEN (USER SPECIFIES THE QUANTITY) */

		/* STEP 13:  CALL THE METHOD TO DISPLAY THE ORDER QUANTITIES */
	}
}
